/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package academico.view.Secretario;

import academico.controller.SecretarioController;
import academico.model.ContatosProfessor;
import academico.model.EspecialidadesProfessor;
import academico.model.JPAUtil;
import academico.model.Professor;
import academico.model.Sala;
import academico.model.Turma;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityNotFoundException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows 11
 */
public class AtualizarSalaSecretario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AtualizarSalaSecretario.class.getName());

    /**
     * Creates new form AtualizarSalaSecretario
     */
    public AtualizarSalaSecretario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        localField = new javax.swing.JTextField();
        capacidadeField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        salvarButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        turmaTable = new javax.swing.JTable();
        pesquisaField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        filtrarButton = new javax.swing.JButton();
        salaBox = new javax.swing.JComboBox<>();
        idField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        alunoCombo = new javax.swing.JComboBox<>();
        professorCombo = new javax.swing.JComboBox<>();
        turmaCombo = new javax.swing.JComboBox<>();
        cursoCombo = new javax.swing.JComboBox<>();
        salaCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        localField.addActionListener(this::localFieldActionPerformed);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Capacidade:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Local:");

        salvarButton1.setBackground(new java.awt.Color(102, 102, 255));
        salvarButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        salvarButton1.setText("SALVAR");
        salvarButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarButton1salvarActionEvent(evt);
            }
        });
        salvarButton1.addActionListener(this::salvarButton1ActionPerformed);

        turmaTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        turmaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Turma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(turmaTable);

        pesquisaField.addActionListener(this::pesquisaFieldActionPerformed);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Digite Turma:");

        filtrarButton.setText("Filtrar");
        filtrarButton.addActionListener(this::filtrarButtonActionPerformed);

        salaBox.setMaximumRowCount(10);
        salaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pressionar Filtrar", " " }));
        salaBox.addActionListener(this::salaBoxalunoActionEvent);

        idField.setFocusable(false);
        idField.setRequestFocusEnabled(false);
        idField.addActionListener(this::idFieldActionPerformed);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Id:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(salvarButton1))
                            .addComponent(capacidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(localField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesquisaField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(filtrarButton)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(localField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtrarButton)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(salaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvarButton1))
                .addGap(347, 347, 347))
        );

        menu.setBackground(new java.awt.Color(153, 153, 153));
        menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 255)));
        menu.setForeground(new java.awt.Color(102, 102, 255));

        alunoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matricular Aluno", "Atualizar Aluno", "Consultar Aluno", " " }));
        alunoCombo.addActionListener(this::alunoComborequisicaoComboEvent);

        professorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Professor", "Atualizar Professor", "Consultar Professor" }));
        professorCombo.addActionListener(this::professorComboEvent);

        turmaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Turma", "Atualizar Turma", "Consultar Turma" }));
        turmaCombo.addActionListener(this::turmaComboEvent);

        cursoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Curso", "Atualizar Curso", "Consultar Curso" }));
        cursoCombo.addActionListener(this::cursoComboEvent);

        salaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Sala", "Atualizar Sala", "Consultar Sala" }));
        salaCombo.addActionListener(this::salaComboEvent);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(alunoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cursoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(professorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(turmaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alunoCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(professorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(turmaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cursoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(salaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localFieldActionPerformed

    private void salvarButton1salvarActionEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarButton1salvarActionEvent
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarButton1salvarActionEvent

    private void salvarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButton1ActionPerformed
        // TODO add your handling code here:

        SecretarioController secretario = new SecretarioController();
        EntityManager em = JPAUtil.getEntityManager();

        try {

            //Pegar lista turma
            List<Turma> listaTurma = new ArrayList<>();
            System.out.println("\nENTRANDO TURMA TABLE\n");
            for (int r=0; r<turmaTable.getRowCount(); r++){

                if (turmaTable.getValueAt(r, 0) != "") {
                    Turma turmaTemp = new Turma();

                    String jpqlTurma = """
                    SELECT t
                    FROM Turma t
                    WHERE t.nome = :turmaNome AND deleted = false
                    """;
                    try {
                        turmaTemp = em.createQuery(jpqlTurma, Turma.class).setParameter("turmaNome", turmaTable.getValueAt(r, 0).toString()).getSingleResult();
                    }
                    catch (EntityNotFoundException e){
                        JOptionPane.showMessageDialog(this, "Turma não encontrada!");
                        e.printStackTrace();
                    }

                    listaTurma.add(turmaTemp);
                }

            }

            Integer capacidadeT = Integer.parseInt(capacidadeField.getText());
            
            
            System.out.println("\nENTRANDO ATUALIZAR SALA, ID: " + idField.getText());
            secretario.atualizarSala(em, Integer.parseInt(idField.getText()), localField.getText(),capacidadeT, listaTurma);

        }
        catch (Exception e ){
            JOptionPane.showMessageDialog(this, "Dados inválidos!");
        }
    }//GEN-LAST:event_salvarButton1ActionPerformed

    private void alunoComborequisicaoComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoComborequisicaoComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(alunoCombo.getSelectedIndex() == 0){
            new RegistrarAlunoSecretario().setVisible(true);

        }
        else if (alunoCombo.getSelectedIndex() == 1){
            new AtualizarAlunoSecretario().setVisible(true);

        }
        else if (alunoCombo.getSelectedIndex() == 2){
            new AtualizarAlunoSecretario().setVisible(true);

        }
    }//GEN-LAST:event_alunoComborequisicaoComboEvent

    private void professorComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(professorCombo.getSelectedIndex() == 0){
            new RegistrarProfessorSecretario().setVisible(true);

        }
        else if (professorCombo.getSelectedIndex() == 1){
            new AtualizarProfessorSecretario().setVisible(true);

        }
        else if (professorCombo.getSelectedIndex() == 2){
            new AtualizarProfessorSecretario().setVisible(true);

        }
    }//GEN-LAST:event_professorComboEvent

    private void turmaComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(turmaCombo.getSelectedIndex() == 0){
            new RegistrarTurmaSecretario().setVisible(true);

        }
        else if (turmaCombo.getSelectedIndex() == 1){
            new AtualizarTurmaSecretario().setVisible(true);

        }
        else if (turmaCombo.getSelectedIndex() == 2){
            new AtualizarTurmaSecretario().setVisible(true);

        }
    }//GEN-LAST:event_turmaComboEvent

    private void cursoComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(cursoCombo.getSelectedIndex() == 0){
            new RegistrarCursoSecretario().setVisible(true);

        }
        else if (cursoCombo.getSelectedIndex() == 1){
            new AtualizarCursoSecretario().setVisible(true);

        }
        else if (cursoCombo.getSelectedIndex() == 2){
            new AtualizarCursoSecretario().setVisible(true);

        }
    }//GEN-LAST:event_cursoComboEvent

    private void salaComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaComboEvent
        // TODO add your handling code here:
        
        this.dispose();
        if(salaCombo.getSelectedIndex() == 0){
            new RegistrarSalaSecretario().setVisible(true);

        }
        else if (salaCombo.getSelectedIndex() == 1){
            new AtualizarSalaSecretario().setVisible(true);

        }
        else if (salaCombo.getSelectedIndex() == 2){
            new AtualizarSalaSecretario().setVisible(true);

        }
    }//GEN-LAST:event_salaComboEvent

    private void pesquisaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaFieldActionPerformed

    private void filtrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarButtonActionPerformed
        // TODO add your handling code here:
        SecretarioController secretario = new SecretarioController();
        EntityManager em = JPAUtil.getEntityManager();
        System.out.println("\nPROFESSOR: " + pesquisaField.getText() + "\n");

        if (!pesquisaField.getText().contentEquals("")) {
            try {
                String jpqlSala = """
                SELECT s
                FROM Sala s
                WHERE s.turma.nome = :turmaNome AND s.deleted = false
                ORDER BY s.local
                """;
                List<Sala> salas = em.createQuery(jpqlSala,Sala.class).setParameter("turmaNome", pesquisaField.getText().toUpperCase()).getResultList();

                for (Sala s : salas){
                    salaBox.addItem(s.getLocal());
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Dados inválidos!");
            }
        } else {
            System.out.println("\n\nENTROU ELSE\n\n");
            JOptionPane.showMessageDialog(this, "Pesquisa sem filtro, todas salas serão disponibilizadas!");

            List<Sala> salas = secretario.consultarSalas(em, null);

            System.out.println("\n\nPASSOU QUERY\n\n");

            for (Sala s : salas){
                salaBox.addItem(s.getLocal());
            }

        }
    }//GEN-LAST:event_filtrarButtonActionPerformed

    private void salaBoxalunoActionEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaBoxalunoActionEvent
        // TODO add your handling code here:
        EntityManager em = JPAUtil.getEntityManager();
        SecretarioController secretario = new SecretarioController();

        Sala s = secretario.consultarSalas(em, salaBox.getSelectedItem().toString()).get(0);
        
        System.out.println("\nINICIOU FIELD\n");
        localField.setText(s.getLocal());
        capacidadeField.setText(String.valueOf(s.getCapacidade()));
        idField.setText(String.valueOf(s.getId()));
        System.out.println("\nTERMINOU FIELD\n");

        //Tabela Turma
        DefaultTableModel modelT = (DefaultTableModel) turmaTable.getModel();
        modelT.setRowCount(0);
        for (Turma t : s.getTurmas()){

            modelT.addRow(new Object[]{
                t.getNome()
            });

        }
        modelT.addRow(new Object[]{""});

    }//GEN-LAST:event_salaBoxalunoActionEvent

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AtualizarSalaSecretario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alunoCombo;
    private javax.swing.JTextField capacidadeField;
    private javax.swing.JComboBox<String> cursoCombo;
    private javax.swing.JButton filtrarButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField localField;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField pesquisaField;
    private javax.swing.JComboBox<String> professorCombo;
    private javax.swing.JComboBox<String> salaBox;
    private javax.swing.JComboBox<String> salaCombo;
    private javax.swing.JButton salvarButton1;
    private javax.swing.JComboBox<String> turmaCombo;
    private javax.swing.JTable turmaTable;
    // End of variables declaration//GEN-END:variables
}
