/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package academico.view.Secretario;

import academico.view.Professor.AtualizarPautaProfessor;
import academico.view.Professor.CriarPautaProfessor;

/**
 *
 * @author Windows 11
 */
public class InicialSecretario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicialSecretario.class.getName());

    /**
     * Creates new form InicialSecretario
     */
    public InicialSecretario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        alunoCombo = new javax.swing.JComboBox<>();
        professorCombo = new javax.swing.JComboBox<>();
        turmaCombo = new javax.swing.JComboBox<>();
        cursoCombo = new javax.swing.JComboBox<>();
        salaCombo = new javax.swing.JComboBox<>();
        disciplinaCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SECRETÁRIO");

        menu.setBackground(new java.awt.Color(153, 153, 153));
        menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 255)));
        menu.setForeground(new java.awt.Color(102, 102, 255));

        alunoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matricular Aluno", "Atualizar Aluno", "Consultar Aluno", " " }));
        alunoCombo.addActionListener(this::alunoComborequisicaoComboEvent);

        professorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Professor", "Atualizar Professor", "Consultar Professor" }));
        professorCombo.addActionListener(this::professorComboEvent);

        turmaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Turma", "Atualizar Turma", "Consultar Turma" }));
        turmaCombo.addActionListener(this::turmaComboEvent);

        cursoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Curso", "Atualizar Curso", "Consultar Curso" }));
        cursoCombo.addActionListener(this::cursoComboEvent);

        salaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Sala", "Atualizar Sala", "Consultar Sala" }));
        salaCombo.addActionListener(this::salaComboEvent);

        disciplinaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Disciplina", "Consultar Disciplinas" }));
        disciplinaCombo.addActionListener(this::disciplinaComboEvent);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(alunoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cursoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(professorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(turmaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(disciplinaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(alunoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turmaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(disciplinaCombo)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alunoComborequisicaoComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoComborequisicaoComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(alunoCombo.getSelectedIndex() == 0){
            new RegistrarAlunoSecretario().setVisible(true);

        }
        else if (alunoCombo.getSelectedIndex() == 1){
            new AtualizarAlunoSecretario().setVisible(true);

        }
        else if (alunoCombo.getSelectedIndex() == 2){
            new AtualizarAlunoSecretario().setVisible(true);

        }
    }//GEN-LAST:event_alunoComborequisicaoComboEvent

    private void professorComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(professorCombo.getSelectedIndex() == 0){
            new RegistrarProfessorSecretario().setVisible(true);

        }
        else if (professorCombo.getSelectedIndex() == 1){
            new AtualizarProfessorSecretario().setVisible(true);

        }
        else if (professorCombo.getSelectedIndex() == 2){
            new AtualizarProfessorSecretario().setVisible(true);

        }
    }//GEN-LAST:event_professorComboEvent

    private void turmaComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(turmaCombo.getSelectedIndex() == 0){
            new RegistrarTurmaSecretario().setVisible(true);

        }
        else if (turmaCombo.getSelectedIndex() == 1){
            new AtualizarTurmaSecretario().setVisible(true);

        }
        else if (turmaCombo.getSelectedIndex() == 2){
            new AtualizarTurmaSecretario().setVisible(true);

        }
    }//GEN-LAST:event_turmaComboEvent

    private void cursoComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(cursoCombo.getSelectedIndex() == 0){
            new RegistrarCursoSecretario().setVisible(true);

        }
        else if (cursoCombo.getSelectedIndex() == 1){
            new AtualizarCursoSecretario().setVisible(true);

        }
        else if (cursoCombo.getSelectedIndex() == 2){
            new AtualizarCursoSecretario().setVisible(true);

        }
    }//GEN-LAST:event_cursoComboEvent

    private void salaComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(salaCombo.getSelectedIndex() == 0){
            new RegistrarSalaSecretario().setVisible(true);

        }
        else if (salaCombo.getSelectedIndex() == 1){
            new AtualizarSalaSecretario().setVisible(true);

        }
        else if (salaCombo.getSelectedIndex() == 2){
            new AtualizarSalaSecretario().setVisible(true);

        }
    }//GEN-LAST:event_salaComboEvent

    private void disciplinaComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinaComboEvent
        // TODO add your handling code here:
        this.dispose();
        if (disciplinaCombo.getSelectedIndex() == 0){
            this.dispose();
            new RegistrarDisciplinaSecretario().setVisible(true);

        }
        else if (disciplinaCombo.getSelectedIndex() == 1){
            this.dispose();
            new ConsultarDisciplinaSecretario().setVisible(true);

        }
    }//GEN-LAST:event_disciplinaComboEvent

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InicialSecretario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alunoCombo;
    private javax.swing.JComboBox<String> cursoCombo;
    private javax.swing.JComboBox<String> disciplinaCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JComboBox<String> professorCombo;
    private javax.swing.JComboBox<String> salaCombo;
    private javax.swing.JComboBox<String> turmaCombo;
    // End of variables declaration//GEN-END:variables
}
