/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package academico.view.Aluno;

import academico.controller.AlunoController;
import academico.model.JPAUtil;
import academico.model.TipoFeedback;
import academico.view.Professor.AtualizarPautaProfessor;
import academico.view.Professor.CriarPautaProfessor;
import academico.view.Professor.FrequenciaProfessor;
import academico.view.Professor.NotaProfessor;
import jakarta.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 11
 */
public class CriarFeedbackAluno extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriarFeedbackAluno.class.getName());

    /**
     * Creates new form CriarFeedbackAluno
     */
    public CriarFeedbackAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackText = new javax.swing.JTextPane();
        conteudoLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        salvarButton = new javax.swing.JButton();
        feedbackCombo = new javax.swing.JComboBox<>();
        menu = new javax.swing.JPanel();
        requisicoesCombo = new javax.swing.JComboBox<>();
        feedbackCombo2 = new javax.swing.JComboBox<>();
        frequenciaButton = new javax.swing.JButton();
        notaButton = new javax.swing.JButton();
        turmaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane1.setViewportView(feedbackText);

        conteudoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        conteudoLabel.setForeground(new java.awt.Color(255, 255, 255));
        conteudoLabel.setText("Feedback");

        dataLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dataLabel.setForeground(new java.awt.Color(255, 255, 255));
        dataLabel.setText("Tipo: ");

        salvarButton.setBackground(new java.awt.Color(102, 102, 255));
        salvarButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        salvarButton.setText("SALVAR");
        salvarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarButtonsalvarActionEvent(evt);
            }
        });

        feedbackCombo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feedbackCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sugestão", "Reclamação" }));

        menu.setBackground(new java.awt.Color(153, 153, 153));
        menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 255)));
        menu.setForeground(new java.awt.Color(102, 102, 255));

        requisicoesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Requisição", "Atualizar Requisição", "Consultar Requisição", " " }));
        requisicoesCombo.addActionListener(this::requisicoesComborequisicaoComboEvent);

        feedbackCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Feedback", "Atualizar Feedback", "Consultar Feedback" }));
        feedbackCombo2.addActionListener(this::feedbackCombo2Event);

        frequenciaButton.setText("Frequência");
        frequenciaButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        frequenciaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frequenciaButtonMouseClicked(evt);
            }
        });
        frequenciaButton.addActionListener(this::frequenciaButtonActionPerformed);

        notaButton.setText("Nota");
        notaButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        notaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notaButtonMouseClicked(evt);
            }
        });
        notaButton.addActionListener(this::notaButtonActionPerformed);

        turmaButton.setText("Turma");
        turmaButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        turmaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turmaButtonMouseClicked(evt);
            }
        });
        turmaButton.addActionListener(this::turmaButtonActionPerformed);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(requisicoesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(feedbackCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(notaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(frequenciaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(turmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requisicoesCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(feedbackCombo2)
            .addComponent(notaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(turmaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(frequenciaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(conteudoLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(dataLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(feedbackCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salvarButton)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(conteudoLabel)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(feedbackCombo)
                            .addComponent(salvarButton))))
                .addContainerGap(355, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonsalvarActionEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarButtonsalvarActionEvent
        // TODO add your handling code here:

        AlunoController aluno = new AlunoController();
        EntityManager em = JPAUtil.getEntityManager();
        TipoFeedback tipo = null;
        try {
 
            switch (feedbackCombo.getSelectedItem().toString()) {
                
                case "Sugestão" -> tipo = TipoFeedback.SUGESTÃO;
                
                case "Reclamação" -> tipo = TipoFeedback.RECLAMAÇÃO;
                
            }
            
            aluno.registrarFeedback(em, feedbackText.getText(), tipo);

        }
        catch (Exception e ){
            JOptionPane.showMessageDialog(this, "Dados inválidos!");
        }

    }//GEN-LAST:event_salvarButtonsalvarActionEvent

    private void requisicoesComborequisicaoComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisicoesComborequisicaoComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(requisicoesCombo.getSelectedIndex() == 0){
            new CriarRequisicaoAluno().setVisible(true);

        }
        else if (requisicoesCombo.getSelectedIndex() == 1){
            new AtualizarRequisicaoAluno().setVisible(true);

        }
        else if (requisicoesCombo.getSelectedIndex() == 2){
            new AtualizarRequisicaoAluno().setVisible(true);

        }
    }//GEN-LAST:event_requisicoesComborequisicaoComboEvent

    private void feedbackCombo2Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackCombo2Event
        // TODO add your handling code here:
        this.dispose();
        if(feedbackCombo.getSelectedIndex() == 0){
            new CriarFeedbackAluno().setVisible(true);

        }
        else if (feedbackCombo.getSelectedIndex() == 1){
            new AtualizarFeedbackAluno().setVisible(true);

        }
        else if (feedbackCombo.getSelectedIndex() == 2){
            new AtualizarFeedbackAluno().setVisible(true);

        }
    }//GEN-LAST:event_feedbackCombo2Event

    private void frequenciaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frequenciaButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ConsultarFrequenciaAluno().setVisible(true);
    }//GEN-LAST:event_frequenciaButtonMouseClicked

    private void frequenciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequenciaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frequenciaButtonActionPerformed

    private void notaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notaButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ConsultarNotaAluno().setVisible(true);
    }//GEN-LAST:event_notaButtonMouseClicked

    private void notaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaButtonActionPerformed

    private void turmaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turmaButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_turmaButtonMouseClicked

    private void turmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaButtonActionPerformed
        // TODO add your handling code here:

        this.dispose();
        new InscreverTurmaAluno().setVisible(true);
    }//GEN-LAST:event_turmaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CriarFeedbackAluno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conteudoLabel;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JComboBox<String> feedbackCombo;
    private javax.swing.JComboBox<String> feedbackCombo2;
    private javax.swing.JTextPane feedbackText;
    private javax.swing.JButton frequenciaButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu;
    private javax.swing.JButton notaButton;
    private javax.swing.JComboBox<String> requisicoesCombo;
    private javax.swing.JButton salvarButton;
    private javax.swing.JButton turmaButton;
    // End of variables declaration//GEN-END:variables
}
