/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package academico.view.Aluno;

import academico.controller.AlunoController;
import academico.controller.SecretarioController;
import academico.model.Aluno;
import academico.model.Disciplina;
import academico.model.JPAUtil;
import academico.model.NotaConsultaDTO;
import academico.model.Professor;
import academico.model.Sala;
import academico.model.Turma;
import academico.model.TurnoType;
import jakarta.persistence.EntityManager;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows 11
 */
public class InscreverTurmaAluno extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InscreverTurmaAluno.class.getName());

    /**
     * Creates new form InscreverTurmaAluno
     */
    public InscreverTurmaAluno() {
        initComponents();
        turmaPrint();
        invisivelBox.setVisible(false);
    }
    
    
    public void turmaPrint(){
        
        AlunoController aluno = new AlunoController();
        EntityManager em = JPAUtil.getEntityManager();

            try { 

                List<Turma> dados = aluno.consultarTurmas(em, null);

                for (Turma t : dados){
                    turmaBox.addItem(t.getNome());
                    invisivelBox.addItem(String.valueOf(t.getId()));
                    
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Dados inválidos");
            }
 
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        horarioField = new javax.swing.JTextField();
        salaField = new javax.swing.JTextField();
        vagasField = new javax.swing.JTextField();
        disciplinaField = new javax.swing.JTextField();
        professorField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        salvarButton1 = new javax.swing.JButton();
        turnoCombo = new javax.swing.JComboBox<>();
        turmaField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        turmaBox = new javax.swing.JComboBox<>();
        invisivelBox = new javax.swing.JComboBox<>();
        menu = new javax.swing.JPanel();
        requisicoesCombo = new javax.swing.JComboBox<>();
        feedbackCombo = new javax.swing.JComboBox<>();
        frequenciaButton = new javax.swing.JButton();
        notaButton = new javax.swing.JButton();
        turmaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        horarioField.setEditable(false);
        horarioField.addActionListener(this::horarioFieldActionPerformed);

        salaField.setEditable(false);

        vagasField.setEditable(false);

        disciplinaField.setEditable(false);
        disciplinaField.addActionListener(this::disciplinaFieldActionPerformed);

        professorField.setEditable(false);
        professorField.addActionListener(this::professorFieldActionPerformed);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Turno:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Horário:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Sala Local:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Professor:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Número de Vagas:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Disciplina:");

        salvarButton1.setBackground(new java.awt.Color(102, 102, 255));
        salvarButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        salvarButton1.setText("INSCREVER");
        salvarButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarButton1salvarActionEvent(evt);
            }
        });
        salvarButton1.addActionListener(this::salvarButton1ActionPerformed);

        turnoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno", "Integral" }));
        turnoCombo.addActionListener(this::turnoComboActionPerformed);

        turmaField.setEditable(false);
        turmaField.addActionListener(this::turmaFieldActionPerformed);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Turma:");

        turmaBox.setMaximumRowCount(10);
        turmaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pressionar Filtrar", " " }));
        turmaBox.addActionListener(this::turmaBoxalunoActionEvent);

        invisivelBox.setMaximumRowCount(10);
        invisivelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cpf" }));
        invisivelBox.addActionListener(this::invisivelBoxalunoActionEvent);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(invisivelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salaField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(professorField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(turmaField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(turmaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 192, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(vagasField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disciplinaField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salvarButton1)
                            .addComponent(turnoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vagasField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(disciplinaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(turnoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(professorField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(salaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(turmaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(157, 157, 157)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarButton1)
                    .addComponent(turmaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(invisivelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(374, 374, 374))
        );

        menu.setBackground(new java.awt.Color(153, 153, 153));
        menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 255)));
        menu.setForeground(new java.awt.Color(102, 102, 255));

        requisicoesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Requisição", "Atualizar Requisição", "Consultar Requisição", " " }));
        requisicoesCombo.addActionListener(this::requisicoesComborequisicaoComboEvent);

        feedbackCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Feedback", "Atualizar Feedback", "Consultar Feedback" }));
        feedbackCombo.addActionListener(this::feedbackComboEvent);

        frequenciaButton.setText("Frequência");
        frequenciaButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        frequenciaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frequenciaButtonMouseClicked(evt);
            }
        });
        frequenciaButton.addActionListener(this::frequenciaButtonActionPerformed);

        notaButton.setText("Nota");
        notaButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        notaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notaButtonMouseClicked(evt);
            }
        });
        notaButton.addActionListener(this::notaButtonActionPerformed);

        turmaButton.setText("Turma");
        turmaButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        turmaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turmaButtonMouseClicked(evt);
            }
        });
        turmaButton.addActionListener(this::turmaButtonActionPerformed);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(requisicoesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(feedbackCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(notaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(frequenciaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(turmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requisicoesCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(feedbackCombo)
            .addComponent(notaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(turmaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(frequenciaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void horarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioFieldActionPerformed

    private void disciplinaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disciplinaFieldActionPerformed

    private void professorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professorFieldActionPerformed

    private void salvarButton1salvarActionEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarButton1salvarActionEvent
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarButton1salvarActionEvent

    private void salvarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButton1ActionPerformed
        // TODO add your handling code here:

        AlunoController aluno = new AlunoController();
        EntityManager em = JPAUtil.getEntityManager();

        try {
    
            String msg = aluno.inscreverEmTurma(em, turmaField.getText());
            JOptionPane.showMessageDialog(this, msg);

        }
        catch (Exception e ){
            JOptionPane.showMessageDialog(this, "Dados inválidos!");
        }
    }//GEN-LAST:event_salvarButton1ActionPerformed

    private void turnoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turnoComboActionPerformed

    private void turmaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turmaFieldActionPerformed

    private void turmaBoxalunoActionEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaBoxalunoActionEvent
        // TODO add your handling code here:
        EntityManager em = JPAUtil.getEntityManager();
        AlunoController aluno = new AlunoController();

        Turma t = aluno.consultarTurmas(em, turmaBox.getSelectedItem().toString()).getLast();

        System.out.println("\nINICIOU FIELD\n");

        if (t.getNome()!= null) turmaField.setText(t.getNome());
        if (t.getNumerovagas( )!= null) vagasField.setText(String.valueOf(t.getNumerovagas()));
        if (t.getSala( )!= null) salaField.setText(t.getSala().getLocal());
        horarioField.setText(String.valueOf(t.getHorario()));
        if (t.getProfessor( )!= null) professorField.setText(t.getProfessor().getNome());
        if (t.getDisciplina( )!= null) disciplinaField.setText(t.getDisciplina().getNome());

        switch (t.getTurno().toString()){
            case "MATUTINO" -> turnoCombo.setSelectedIndex(0);
            case "VESPERTINO" -> turnoCombo.setSelectedIndex(1);
            case "NOTURNO" -> turnoCombo.setSelectedIndex(2);
            case "INTEGRAL" -> turnoCombo.setSelectedIndex(3);
        }

        System.out.println("\nTERMINOU FIELD\n");
    }//GEN-LAST:event_turmaBoxalunoActionEvent

    private void invisivelBoxalunoActionEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invisivelBoxalunoActionEvent
        // TODO add your handling code here:
    }//GEN-LAST:event_invisivelBoxalunoActionEvent

    private void requisicoesComborequisicaoComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisicoesComborequisicaoComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(requisicoesCombo.getSelectedIndex() == 0){
            new CriarRequisicaoAluno().setVisible(true);

        }
        else if (requisicoesCombo.getSelectedIndex() == 1){
            new AtualizarRequisicaoAluno().setVisible(true);

        }
        else if (requisicoesCombo.getSelectedIndex() == 2){
            new AtualizarRequisicaoAluno().setVisible(true);

        }
    }//GEN-LAST:event_requisicoesComborequisicaoComboEvent

    private void feedbackComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(feedbackCombo.getSelectedIndex() == 0){
            new CriarFeedbackAluno().setVisible(true);

        }
        else if (feedbackCombo.getSelectedIndex() == 1){
            new AtualizarFeedbackAluno().setVisible(true);

        }
        else if (feedbackCombo.getSelectedIndex() == 2){
            new AtualizarFeedbackAluno().setVisible(true);

        }
    }//GEN-LAST:event_feedbackComboEvent

    private void frequenciaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frequenciaButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ConsultarFrequenciaAluno().setVisible(true);

    }//GEN-LAST:event_frequenciaButtonMouseClicked

    private void frequenciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequenciaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frequenciaButtonActionPerformed

    private void notaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notaButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ConsultarNotaAluno().setVisible(true);
    }//GEN-LAST:event_notaButtonMouseClicked

    private void notaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaButtonActionPerformed

    private void turmaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turmaButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_turmaButtonMouseClicked

    private void turmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaButtonActionPerformed
        // TODO add your handling code here:

        this.dispose();
        new InscreverTurmaAluno().setVisible(true);

    }//GEN-LAST:event_turmaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InscreverTurmaAluno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField disciplinaField;
    private javax.swing.JComboBox<String> feedbackCombo;
    private javax.swing.JButton frequenciaButton;
    private javax.swing.JTextField horarioField;
    private javax.swing.JComboBox<String> invisivelBox;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel menu;
    private javax.swing.JButton notaButton;
    private javax.swing.JTextField professorField;
    private javax.swing.JComboBox<String> requisicoesCombo;
    private javax.swing.JTextField salaField;
    private javax.swing.JButton salvarButton1;
    private javax.swing.JComboBox<String> turmaBox;
    private javax.swing.JButton turmaButton;
    private javax.swing.JTextField turmaField;
    private javax.swing.JComboBox<String> turnoCombo;
    private javax.swing.JTextField vagasField;
    // End of variables declaration//GEN-END:variables
}
