/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package almoxarifado.view;

/**
 *
 * @author Windows 11
 */
public class InicialAlmoxarifado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicialAlmoxarifado.class.getName());

    /**
     * Creates new form InicialAlmoxarifado
     */
    public InicialAlmoxarifado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        produtoCombo = new javax.swing.JComboBox<>();
        bemCombo = new javax.swing.JComboBox<>();
        movimentacaoCombo = new javax.swing.JComboBox<>();
        baixaCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALMOXARIFADO");

        menu.setBackground(new java.awt.Color(153, 153, 153));
        menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 102, 51)));
        menu.setForeground(new java.awt.Color(255, 0, 204));

        produtoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matricular Aluno", "Atualizar Aluno", "Consultar Aluno", " " }));
        produtoCombo.addActionListener(this::produtoComborequisicaoComboEvent);

        bemCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Bem", "Atualizar Bem", "Consultar Bem" }));
        bemCombo.addActionListener(this::bemComboEvent);

        movimentacaoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Movimentacao", "Atualizar Movimentacao", "Consultar Movimentacao", " " }));
        movimentacaoCombo.addActionListener(this::movimentacaoComboEvent);

        baixaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Baixa", "Atualizar Baixa", "Consultar Baixa" }));
        baixaCombo.addActionListener(this::baixaComboEvent);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(produtoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bemCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(movimentacaoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(baixaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bemCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movimentacaoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baixaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void produtoComborequisicaoComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoComborequisicaoComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(produtoCombo.getSelectedIndex() == 0){
            new CadastrarProduto().setVisible(true);

        }
        else if (produtoCombo.getSelectedIndex() == 1){
            new AtualizarProduto().setVisible(true);

        }
        else if (produtoCombo.getSelectedIndex() == 2){
            new AtualizarProduto().setVisible(true);

        }
    }//GEN-LAST:event_produtoComborequisicaoComboEvent

    private void bemComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bemComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(bemCombo.getSelectedIndex() == 0){
            new CadastrarBem().setVisible(true);

        }
        else if (bemCombo.getSelectedIndex() == 1){
            new AtualizarBem().setVisible(true);

        }
        else if (bemCombo.getSelectedIndex() == 2){
            new AtualizarBem().setVisible(true);

        }
    }//GEN-LAST:event_bemComboEvent

    private void movimentacaoComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movimentacaoComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(movimentacaoCombo.getSelectedIndex() == 0){
            new CadastrarMovimentacao().setVisible(true);

        }
        else if (movimentacaoCombo.getSelectedIndex() == 1){
            new AtualizarMovimentacao().setVisible(true);

        }
        else if (movimentacaoCombo.getSelectedIndex() == 2){
            new AtualizarMovimentacao().setVisible(true);

        }
    }//GEN-LAST:event_movimentacaoComboEvent

    private void baixaComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baixaComboEvent
        // TODO add your handling code here:
        
        this.dispose();
        if(baixaCombo.getSelectedIndex() == 0){
            new CadastrarBaixa().setVisible(true);

        }
        else if (baixaCombo.getSelectedIndex() == 1){
            new AtualizarBaixa().setVisible(true);

        }
        else if (baixaCombo.getSelectedIndex() == 2){
            new AtualizarBaixa().setVisible(true);

        }
        
    }//GEN-LAST:event_baixaComboEvent

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InicialAlmoxarifado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> baixaCombo;
    private javax.swing.JComboBox<String> bemCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JComboBox<String> movimentacaoCombo;
    private javax.swing.JComboBox<String> produtoCombo;
    // End of variables declaration//GEN-END:variables
}
