/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.view;

import biblioteca.controller.BibliotecarioController;
import biblioteca.controller.UsuarioBibliotecaController;
import biblioteca.model.Notificacao;
import biblioteca.model.Obra;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 11
 */
public class ConsultarNotificacoesBibliotecario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultarNotificacoesBibliotecario.class.getName());

    /**
     * Creates new form ConsultarNotificacoesBibliotecario
     */
    public ConsultarNotificacoesBibliotecario() {
        initComponents();
        invisivelBox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loginField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tipoBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        usuarioBox = new javax.swing.JComboBox<>();
        mensagemText = new javax.swing.JTextField();
        pesquisaField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        invisivelBox = new javax.swing.JComboBox<>();
        loginBox = new javax.swing.JComboBox<>();
        filtrarButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        deletedCheck = new javax.swing.JCheckBox();
        criacaoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salvarButton1 = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        obraCombo = new javax.swing.JComboBox<>();
        notificacaoCombo = new javax.swing.JComboBox<>();
        usuarioButton = new javax.swing.JButton();
        bibliotecarioCombo = new javax.swing.JComboBox<>();
        emprestimoCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        loginField.setEditable(false);
        loginField.addActionListener(this::loginFieldActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Usuario Login:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mensagem:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("TipoNotificacao:");

        tipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível", "Indisponível" }));
        tipoBox.addActionListener(this::tipoBoxActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("TipoUsuario:");

        usuarioBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Professor" }));
        usuarioBox.addActionListener(this::usuarioBoxActionPerformed);

        mensagemText.setEditable(false);
        mensagemText.addActionListener(this::mensagemTextActionPerformed);

        pesquisaField.addActionListener(this::pesquisaFieldActionPerformed);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Digite Login para busca:");

        invisivelBox.setMaximumRowCount(10);
        invisivelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pressionar Filtrar", "" }));
        invisivelBox.addActionListener(this::invisivelBoxActionPerformed);

        loginBox.setMaximumRowCount(10);
        loginBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pressionar Filtrar", " " }));
        loginBox.addActionListener(this::loginBoxalunoActionEvent);

        filtrarButton.setText("Filtrar");
        filtrarButton.addActionListener(this::filtrarButtonActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Deletar:");

        deletedCheck.setText("Marque para deletar\n");
        deletedCheck.addActionListener(this::deletedCheckActionPerformed);

        criacaoField.setEditable(false);
        criacaoField.addActionListener(this::criacaoFieldActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Data de Criação:");

        salvarButton1.setBackground(new java.awt.Color(200, 177, 43));
        salvarButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        salvarButton1.setText("SALVAR");
        salvarButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarButton1salvarActionEvent(evt);
            }
        });
        salvarButton1.addActionListener(this::salvarButton1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(usuarioBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletedCheck))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(criacaoField))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mensagemText, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salvarButton1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(invisivelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loginBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pesquisaField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(filtrarButton)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(usuarioBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(criacaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(mensagemText))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(118, 118, 118)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(deletedCheck))
                        .addGap(458, 458, 458))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtrarButton)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invisivelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(salvarButton1)
                        .addGap(304, 304, 304))))
        );

        menu.setBackground(new java.awt.Color(153, 153, 153));
        menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(200, 177, 43)));
        menu.setForeground(new java.awt.Color(255, 0, 204));

        obraCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cadastrar Obra", "Atualizar Obra", "Consultar Obra", " " }));
        obraCombo.addActionListener(this::obraComborequisicaoComboEvent);

        notificacaoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enviar Notificação", "Consultar Notificação" }));
        notificacaoCombo.addActionListener(this::notificacaoComboEvent);

        usuarioButton.setText("Consultar Usuário");
        usuarioButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(0, 0, 0)));
        usuarioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioButtonMouseClicked(evt);
            }
        });
        usuarioButton.addActionListener(this::usuarioButtonActionPerformed);

        bibliotecarioCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cadastrar Bibliotecário", "Atualizar Bibliotecário", "Consultar Bibliotecário" }));
        bibliotecarioCombo.addActionListener(this::bibliotecarioComboEvent);

        emprestimoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cadastrar Empréstimo", "Atualizar Empréstimo", "Consultar Empréstimo", " " }));
        emprestimoCombo.addActionListener(this::emprestimoComboActionPerformed);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(obraCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(notificacaoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bibliotecarioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emprestimoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bibliotecarioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(notificacaoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emprestimoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(obraCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFieldActionPerformed

    private void tipoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoBoxActionPerformed

    private void usuarioBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioBoxActionPerformed

    private void mensagemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensagemTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensagemTextActionPerformed

    private void obraComborequisicaoComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obraComborequisicaoComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(obraCombo.getSelectedIndex() == 0){
            new CadastrarObraBibliotecario().setVisible(true);

        }
        else if (obraCombo.getSelectedIndex() == 1){
            new AtualizarObraBibliotecario().setVisible(true);

        }
        else if (obraCombo.getSelectedIndex() == 2){
            new AtualizarObraBibliotecario().setVisible(true);

        }
    }//GEN-LAST:event_obraComborequisicaoComboEvent

    private void notificacaoComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificacaoComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(notificacaoCombo.getSelectedIndex() == 0){
            new EnviarNotificacaoBibliotecario().setVisible(true);

        }
        else if (notificacaoCombo.getSelectedIndex() == 1){
            new ConsultarNotificacoesBibliotecario().setVisible(true);

        }
        else if (notificacaoCombo.getSelectedIndex() == 2){
            new ConsultarNotificacoesBibliotecario().setVisible(true);

        }
    }//GEN-LAST:event_notificacaoComboEvent

    private void usuarioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ConsultarUsuario().setVisible(true);
    }//GEN-LAST:event_usuarioButtonMouseClicked

    private void usuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ConsultarUsuario().setVisible(true);
    }//GEN-LAST:event_usuarioButtonActionPerformed

    private void bibliotecarioComboEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecarioComboEvent
        // TODO add your handling code here:
        this.dispose();
        if(bibliotecarioCombo.getSelectedIndex() == 0){
            new CadastrarBibliotecario().setVisible(true);

        }
        else if (bibliotecarioCombo.getSelectedIndex() == 1){
            new AtualizarBibliotecario().setVisible(true);

        }
        else if (bibliotecarioCombo.getSelectedIndex() == 2){
            new AtualizarBibliotecario().setVisible(true);

        }
    }//GEN-LAST:event_bibliotecarioComboEvent

    private void pesquisaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaFieldActionPerformed

    private void invisivelBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invisivelBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invisivelBoxActionPerformed

    private void loginBoxalunoActionEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBoxalunoActionEvent
        // TODO add your handling code here:

        BibliotecarioController bibliotecario = new BibliotecarioController();

        Notificacao n = bibliotecario.consultarNotificacaoId(Integer.parseInt(invisivelBox.getItemAt(loginBox.getSelectedIndex())));

        loginField.setText(n.getUsuario().getLogin());
        criacaoField.setText(String.valueOf(n.getCreated_at()));
        usuarioBox.setSelectedItem(n.getTipoUsuario());
        tipoBox.setSelectedItem(n.getTipo());
        
        mensagemText.setText(n.getMensagem());
        
    }//GEN-LAST:event_loginBoxalunoActionEvent

    private void filtrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarButtonActionPerformed
        // TODO add your handling code here:

        BibliotecarioController bibliotecario = new BibliotecarioController();
        System.out.println("\n LOGIN: " + pesquisaField.getText() + "\n");

        if (!pesquisaField.getText().contentEquals("")) {
            try {

                List<Notificacao> notificacoes = bibliotecario.consultarNotificacao(pesquisaField.getText());

                for (Notificacao n : notificacoes) {
                    loginBox.addItem(n.getUsuario().getLogin());
                    invisivelBox.addItem(String.valueOf(n.getId()));
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Dados inválidos!");
            }

        } else {

            List<Notificacao> notificacoes = bibliotecario.consultarNotificacao(null);
             JOptionPane.showMessageDialog(this, "Nenhum filtro fornecido, todas notificações exibidas!");

            for (Notificacao n : notificacoes) {
                    loginBox.addItem(n.getUsuario().getLogin());
                    invisivelBox.addItem(String.valueOf(n.getId()));
            }

        }
    }//GEN-LAST:event_filtrarButtonActionPerformed

    private void deletedCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletedCheckActionPerformed

    private void criacaoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criacaoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criacaoFieldActionPerformed

    private void salvarButton1salvarActionEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarButton1salvarActionEvent
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarButton1salvarActionEvent

    private void salvarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButton1ActionPerformed
        // TODO add your handling code here:

        BibliotecarioController bibliotecario = new BibliotecarioController();

        try {
            Integer notificacaoId = Integer.parseInt(invisivelBox.getItemAt(loginBox.getSelectedIndex()));

            bibliotecario.deletarNotificacao(notificacaoId, deletedCheck.isSelected());

        }
        catch (Exception e ){
            JOptionPane.showMessageDialog(this, "Dados inválidos!");
        }
    }//GEN-LAST:event_salvarButton1ActionPerformed

    private void emprestimoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimoComboActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        if(emprestimoCombo.getSelectedIndex() == 0){
            new CadastrarEmprestimo1().setVisible(true);

        }
        else if (bibliotecarioCombo.getSelectedIndex() == 1){
            new AtualizarEmprestimo().setVisible(true);

        }
        else if (bibliotecarioCombo.getSelectedIndex() == 2){
            new AtualizarEmprestimo().setVisible(true);

        }
    }//GEN-LAST:event_emprestimoComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultarNotificacoesBibliotecario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bibliotecarioCombo;
    private javax.swing.JTextField criacaoField;
    private javax.swing.JCheckBox deletedCheck;
    private javax.swing.JComboBox<String> emprestimoCombo;
    private javax.swing.JButton filtrarButton;
    private javax.swing.JComboBox<String> invisivelBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> loginBox;
    private javax.swing.JTextField loginField;
    private javax.swing.JTextField mensagemText;
    private javax.swing.JPanel menu;
    private javax.swing.JComboBox<String> notificacaoCombo;
    private javax.swing.JComboBox<String> obraCombo;
    private javax.swing.JTextField pesquisaField;
    private javax.swing.JButton salvarButton1;
    private javax.swing.JComboBox<String> tipoBox;
    private javax.swing.JComboBox<String> usuarioBox;
    private javax.swing.JButton usuarioButton;
    // End of variables declaration//GEN-END:variables
}
